---
title: "CE091 - Métodos de Pesquisa"
output:
  html_document:
    toc: false
---

```{r setup, include=FALSE, cache=FALSE}
source("setup_knitr.R")
```

<!-- <div class="alert alert-danger" role="alert"> -->
<!-- </div> -->

# Detalhes da oferta da disciplina

- **Curso:** Estatística
- **Período:** primeiro semestre de 2021 (*online*)
- **Professor Responsável:** [Fernando de Pol Mayer][],
  [LEG][]/DEST/UFPR
- **Horários e Locais:**
  - Sexta, 19:00 - 21:00h, **Teams**
<!-- - **Horários de atendimento dos professores:** -->
<!--     - Segundas, 15:30 - 19:00 (preferenciais). Outros horários -->
<!--       podem ser agendados previamente por email. -->
- **Frequência**: de acordo com as normas da Universidade, mínimo de 75%
- **Avaliação**:
  - Elaboração de um projeto de pesquisa (será avaliada a parte escrita
    e a apresentação/didática)
  - Apresentação e discussão de artigos científicos
  - Atividades complementares
  - Participação nas aulas
- **Datas importantes:**
    - **08/10/2021**: Início das aulas
    - **17/12/2021**: Final das aulas
    - **22/12/2021**: Exame final

# Ojetivos

O objetivo desta disciplina é capacitar os alunos em conceitos básicos
de técnicas de pesquisa que permitam a análise crítica e o
desenvolvimento de trabalhos científicos. Mais especificamente:

- Estimular o pensamento crítico
- Entender o papel da Estatística como lógica da ciência
- Compreender os diferentes formatos de pesquisas científicas
- Dominar ferramentas que auxiliem na elaboração de pesquisas

# Programa

1. **Filosofia da Ciência**: Questões gerais sobre ciência e
conhecimento científico. Introdução à filosofia da ciência e ao método
científico. Lógica dedutiva e indutiva. O problema da indução. Exposição
às diferentes teorias científicas: o falsificacionismo de Popper, os
paradigmas de Kuhn e os programas de pesquisa de Lakatos. Introdução à
filosofia da Estatística.
2. **Métodos de pesquisa**: Aspectos teóricos e conceituais:
conceitos-base e construção do conhecimento. A pesquisa científica.
Tipos de pesquisa. A construção da pesquisa. Estrutura do projeto de
pesquisa.
3. **Ferramentas para pesquisa científica**: Formatação de projeto de
pesquisa e TCC. Templates. Gerenciamento de referências bibliográficas.
Pesquisa reproduzível. Ferramentas para pesquisa reproduzível (renv,
knitr, rmarkdown).

# Ementa

Ética e Meio Ambiente. Relações Ciência, Tecnologia e Sociedade. Métodos
de Pesquisa. Elaboração de Projeto e Relatório de Pesquisa. Referências
Bibliográficas. Prática de Pesquisa.


<!-- links -->

[Fernando de Pol Mayer]: http://leg.ufpr.br/~fernandomayer
[LEG]: http://www.leg.ufpr.br
