---
title: "Referências Bibliográficas"
output:
  html_document:
    toc: false
---

## Referências básicas

#### Metodologia científica

- Gerhardt, TE; Silveira, DT. [Métodos de
   Pesquisa](https://www.lume.ufrgs.br/handle/10183/52806).
   Porto Alegre: Editora da UFRGS, 2009.
- Heard, SB. **The Scientist`s Guide to Writing – How to Write More
Easily and Effectively throughout Your Scientific Career**. Princeton:
Princeton University Press, 2016.
- Marconi, MA; Lakatos, EM. **Fundamentos de metodologia científica**.
  São Paulo: Atlas, 2016.
- Pereira, MG. **Artigos Científicos - Como Redigir, Publicar e
  Avaliar**. Rio de Janeiro: Guanabara Koogan, 2011.

#### Pesquisa reproduzível

- Gandrud, C. **Reproducible research with R and RStudio**. Boca Raton:
  Chapman & Hall/CRC, 2015.
- Xie, Y. **Dynamic documents with R and knitr**. Boca Raton: Chapman &
  Hall/CRC, 2015.

#### Filosofia da ciência

- Chalmers, AF. **O que é ciência afinal?**. São Paulo:
  Brasiliense, 1993.
- Dutra, LHA. **Introdução à teoria da ciência**. Florianópolis: Editora
  da UFSC, 2017.

## Referências complementares

#### Metodologia científica

- Eco, U. **Como se faz uma tese**. São Paulo: Perspectiva, 2016.
- Marconi, MA; Lakatos, EM. **Metodologia do trabalho científico**. São
  Paulo: Atlas, 2015.
- Wallwork, A. **English for writing research papers**. Nova Iorque:
  Springer, 2011.

#### Pesquisa reproduzível

- Kitzes, J; Turek, D; Deniz, F. (Eds.). [The Practice of Reproducible
  Research: Case Studies and Lessons from the Data-Intensive
  Sciences](https://www.practicereproducibleresearch.org/). Oakland, CA:
  University of California Press, 2018.
- Stodden, V; Leisch, F; & Peng, RD. Implementing reproducible research.
  Boca Raton: Chapman & Hall/CRC, 2014.
- Xie, Y. [bookdown: Authoring Books and Technical Documents with R
Markdown](https://bookdown.org/yihui/bookdown/). Boca Raton: Chapman &
Hall/CRC, 2016.
- Xie, Y; Allaire, JJ; Grolemund, G. [R Markdown: The Definitive
  Guide](https://bookdown.org/yihui/rmarkdown/). Boca Raton: Chapman &
  Hall/CRC, 2018.

#### Filosofia da ciência

- Alves, R. **Filosofia da ciência: introdução ao jogo e a suas
  regras**. São Paulo: Loyola, 2007.
- Box, GEP; Hunter, JS; Hunter, WG. [Statistics for experimenters:
  Design Innovation and Discovery](http://statisticsforexperimenters.net).
  Londres: John Wiley & Sons, 2005.
- Costa, N. **Lógica indutiva e probabilidade**. São Paulo:
  Hucitec, 2008.
- Demo, P. **Introdução à metologia da ciência**. São Paulo:
  Atlas, 1985.
- Feyerabend, P. **Contra o método**. São Paulo: Editora da UNESP, 2011.
- Jaynes, ET. **Probability theory: the logic of science**. Cambridge
  University Press, 2003.
- Hilborn, R; Mangel, M. [The ecological detective: confronting models
  with data](http://press.princeton.edu/titles/5987.html). Princeton
  University Press, 1997.
- Jeffreys, H. **Scientific inference**. Cambridge: Cambridge University
  Press, 1957.
- Kuhn, TS. **A estrutura das revoluções científicas**. São Paulo:
  Perspectiva, 2011.
- Pereira, JCR. **Bioestatística em outras palavras**. São Paulo:
  Edusp, 2010.
- Popper, K. **A lógica da pesquisa científica**. São Paulo:
  Cultrix, 2013.
- **The Stanford Encyclopedia of Philosophy** (textos *online*
  selecionados):
  - Andersen, H; Hepburn, B, [Scientific Method](https://plato.stanford.edu/archives/sum2016/entries/scientific-method/), The Stanford Encyclopedia of Philosophy (Summer 2016 Edition), Edward N. Zalta (ed.).
  - Frigg, R; Hartmann, S, [Models in Science](https://plato.stanford.edu/archives/spr2020/entries/models-science/), The Stanford Encyclopedia of Philosophy (Spring 2020 Edition), Edward N. Zalta (ed.).
  - Hájek, A, [Interpretations of Probability](https://plato.stanford.edu/archives/fall2019/entries/probability-interpret/), The Stanford Encyclopedia of Philosophy (Fall 2019 Edition), Edward N. Zalta (ed.).
  - Hansson, SO, [Science and Pseudo-Science](https://plato.stanford.edu/archives/sum2017/entries/pseudo-science/), The Stanford Encyclopedia of Philosophy (Summer 2017 Edition), Edward N. Zalta (ed.).
  - Romeijn, J-W, [Philosophy of Statistics](https://plato.stanford.edu/archives/spr2017/entries/statistics/), The Stanford Encyclopedia of Philosophy (Spring 2017 Edition), Edward N. Zalta (ed.).

**Nota:** existem diversos textos compatíveis com o programa do curso.
Consulte o professor sobre a adequação de qualquer outra referência
bibliográfica.

## Artigos

#### Metodologia científica

- Keshav, S. (2007). [How to read a paper](https://doi.org/10.1145/1273445.1273458). Computer Communication Review, 37(3), 83–84.

#### Pesquisa reproduzível

- Blischak, J. D., Davenport, E. R., & Wilson, G. (2016). [A Quick
Introduction to Version Control with Git and
GitHub](https://doi.org/10.1371/journal.pcbi.1004668). PLOS
Computational Biology, 12(1).
- Gentleman, R., & Temple Lang, D. (2007). [Statistical Analyses and
  Reproducible Research](https://doi.org/10.1198/106186007X178663).
  Journal of Computational and Graphical Statistics, 16(1), 1–23.
- Peng, R. D. (2011). [Reproducible research in computational
science](https://doi.org/10.1126/science.1213847). Science, 334(6060),
1226–1227.
- Perkel, J. M. (2018). [A toolkit for data transparency takes
shape](https://doi.org/10.1038/d41586-018-05990-5). Nature, 560(7719),
513–515.
- Powers, S. M., & Hampton, S. E. (2019). [Open science,
reproducibility, and transparency in
ecology](https://doi.org/10.1002/eap.1822). Ecological Applications,
29(1).
- Stodden, V., Seiler, J., & Ma, Z. (2018). [An empirical analysis of
  journal policy effectiveness for computational
  reproducibility](https://doi.org/10.1073/pnas.1708290115). Proceedings
  of the National Academy of Sciences of the United States of America,
  115(11), 2584–2589.
- Wilson, G., et al. (2014). [Best Practices for Scientific
Computing](https://doi.org/10.1371/journal.pbio.1001745). PLoS Biology,
12(1).

#### Filosofia da ciência (estatística)

- Berger, J. O. (2003). [Could Fisher, Jeffreys and Neyman have agreed
on testing?](https://doi.org/10.1214/ss/1056397485) Statistical Science,
18(1), 1–32.
- Box, G. E. P. (1976). [Science and
statistics](https://doi.org/10.1080/01621459.1976.10480949). Journal of
the American Statistical Association, 71(356), 791–799.
- Good, I. J. (1988). [The interface between statistics and philosophy
of science](https://doi.org/10.1214/ss/1177012754). Statistical Science,
3(4), 386–398.
- Hacking, I. (1964). [On the foundations of
statistics](https://doi.org/10.1093/bjps/XV.57.1). British Journal for
the Philosophy of Science, 15(57), 1–26.
- Lindley, D. V. (2000). [The Philosophy of
Statistics](https://doi.org/10.1111/1467-9884.00238). Journal of the
Royal Statistical Society: Series D (The Statistician), 49(3), 293–337.
- Mayo, D. G. (1980). [The Philosophical Relevance of
Statistics](https://doi.org/10.2307/192556). PSA: Proceedings of the
Biennial Meeting of the Philosophy of Science Association, Vol. 1980,
pp. 97–109.
- Robert, C. P., Chopin, N., & Rousseau, J. (2009). [Harold Jeffreys's
  Theory of Probability Revisited](https://doi.org/10.1214/09-STS284).
  Statistical Science, 24(2), 141–172.
- Silveira, F. (1989). [A filosofia de Karl Popper e suas implicações
no ensino da
ciência](https://periodicos.ufsc.br/index.php/fisica/article/view/7713/14577).
Caderno Brasileiro de Ensino de Física, 6(2), 148–162.
- Steel, E. A., Liermann, M., & Guttorp, P. (2019). [Beyond
Calculations: A Course in Statistical
Thinking](https://doi.org/10.1080/00031305.2018.1505657). The American
Statistician, 73, 392–401.

## Referências *online*

- [Aeon](https://aeon.co): "online sanctuary for serious thinking".
- [Stanford Encyclopedia of Philosophy](https://plato.stanford.edu/).
-  *Blog* sobre [Metodologia
   Científica](https://blog.fastformat.co/category/metodologia-cientifica/)
   (em português).
- [Open Access Philosophy](http://www.wi-phi.com/).
- [Portal da escrita
  científica](http://www.escritacientifica.sc.usp.br/) - USP - São Carlos.
- Disciplina [Métodos de
  Pesquisa](http://www.leg.ufpr.br/doku.php/disciplinas:ce091-2017-01)
  oferecida no primeiro semestre de 2017 pelo Prof. Paulo Justiniano
  Ribeiro Jr.
- [Playlist do Youtube](https://www.youtube.com/playlist?list=PLId4vyPr4QR2F3rGM3ppKPD7bNaVAdS7F). Métodos de pesquisa (2018/1). Disciplina Transversal - PRPPG - UFPR.
- [Playlist do Youtube](https://www.youtube.com/playlist?list=PLId4vyPr4QR2s36S9B1l4yNXQyYAgkNVw). Métodos Estatísticos em Pesquisa Cientifica (2019/1). Disciplina Transversal - PRPPG - UFPR.
- [Playlist do Youtube](https://www.youtube.com/playlist?list=PLId4vyPr4QR0mUf1Bnt6K8Vp0li4e-2_E). Filosofias da Ciência e da Tecnologia (2019/1).  Disciplina Transversal - PRPPG - UFPR.
- [Playlist do Youtube](https://www.youtube.com/playlist?list=PLId4vyPr4QR0Esu9JQpDbqG801nZygcr7).Metodologia de Pesquisa Científica (2019/2). Disciplina Transversal - PRPPG - UFPR.

## Leituras complementares

- Huff, D.
  [Como mentir com estatística](http://www.intrinseca.com.br/livro/624/).
  Rio de Janeiro: Intrínseca, 2016.
- McInerny, DQ. **Use a lógica: um guia para o pensamento eficaz**. Rio
  de Janeiro: BestSeller, 2007.
- Monasterio, L. **Técnicas avançadas de sobrevivência na
  universidade**. Campinas: Vide Editorial, 2017.
- Oakley, B.
  [Aprendendo a aprender. Como ter sucesso em matemática, ciências ou qualquer outra matéria](http://www.infopress.com.br).
  São Paulo: Infopress, 2015.
- Pólya, G.
  [How to solve it](https://www.penguin.co.uk/books/12619/how-to-solve-it).
  London: Penguin Books, 1990.
- Salsburg, D.
  [Uma senhora toma chá. Como a estatística revolucionou a ciência no século XX](http://www.zahar.com.br/livro/uma-senhora-toma-cha).
  Rio de Janeiro: Zahar, 2009.
- Spiegelhalter, D. [The art of Statistics: learning from
  data](https://www.penguin.co.uk/books/294/294857/learning-from-data/9780241258767.html). London: Pelican, 2019.
- Wheelan, C.
  [Estatística: o que é, para que serve, como funciona](http://www.zahar.com.br/livro/estatistica).
  Rio de Janeiro: Zahar, 2016.
