---
title: "Origens do conhecimento"
subtitle: "Senso comum e saber científico"
author: |
  | Fernando de Pol Mayer (LEG/DEST/UFPR)
  | Baseado no material dos Profs. Carlos Soares e Paulo Lana (CEM/UFPR)
date: "2020-03-06"
# bibliography: bib/ref.bib
output:
  xaringan::moon_reader:
    css: ["default", "fc.css", "fc-fonts.css"]
    self_contained: FALSE
    nature:
      highlightStyle: github
      highlightLines: TRUE
      countIncrementalSlides: FALSE
---

# Introdução

CONHECIMENTO DO


“SENSO COMUM”


e o


“SABER CIENTÍFICO”


IDÉIAS GERAIS SOBRE O CONHECIMENTO

O CONHECIMENTO

As idéias e os conceitos que formamos a respeito dos fenômenos da natureza e fatos sociais

(os objetos do conhecimento)

vão formando o


CONJUNTO DE NOSSAS EXPERIÊNCIAS


Este conjunto de experiências é o


CONHECIMENTO,


uma espécie de


REPERTÓRIO DE INFORMAÇÕES


que nos orienta na vida ...

IDÉIAS GERAIS SOBRE O CONHECIMENTO

Os objetos do conhecimento podem ser:



MATERIAIS (os objetos, estruturas e os processos)


ou


NÃO MATERIAIS (as idéias e conceitos)

IDÉIAS GERAIS SOBRE O CONHECIMENTO


A OBSERVAÇÃO

(EMPIRISMO)



COMO ACENDER O FOGO -
(prática repetitiva, experimentalismo)


foi culturalmente transmitido


IDÉIAS GERAIS SOBRE O CONHECIMENTO

AS LIMITAÇÕES DO CONHECIMENTO

Freqüentemente nosso repertório de informações


NÃO É SUFICIENTE OU SATISFATÓRIO


para que entendamos o que está acontecendo



IDÉIAS GERAIS SOBRE O CONHECIMENTO

Surgem aí os


QUESTIONAMENTOS (OU PROBLEMAS)


como


INTERROGAÇÕES


que pedem soluções ...


Novos conhecimentos são necessários para enfrentar estes novos problemas

IDÉIAS GERAIS SOBRE O CONHECIMENTO

AS LIMITAÇÕES DO CONHECIMENTO

PARA QUE SERVE O


CONHECIMENTO?

IDÉIAS GERAIS SOBRE O CONHECIMENTO

Descrever os objetos da natureza e os fatos sociais


SABER COMO FUNCIONAM ESTES OBJETOS


E


FATOS


IDÉIAS GERAIS SOBRE O CONHECIMENTO

PARA QUE SERVE O CONHECIMENTO?

Controlar melhor estes objetos



Fazer as melhores PREVISÕES sobre estes objetos no tempo e no espaço

IDÉIAS GERAIS SOBRE O CONHECIMENTO

PARA QUE SERVE O CONHECIMENTO?

O CONHECIMENTO DO “SENSO COMUM” E O “SABER CIENTÍFICO”
O que é o conhecimento do senso comum?


O que é saber científico?

(1) A intuição (2) A tradição (3) A autoridade
OS TIPOS DE CONHECIMENTO DO “SENSO COMUM”

SENSO COMUM

(1) A INTUIÇÃO
A intuição é a percepção imediata,

sem necessidade de intervenção do raciocínio





SENSO COMUM

Exemplos do conhecimento intuitivo:



o fogo queima/as coisas caem


SENSO COMUM

Qual é a base do

CONHECIMENTO INTUITIVO?


... A simples observação ...


... e as demais percepções sensoriais ...

SENSO COMUM

O conhecimento intuitivo é útil?

SENSO COMUM

INTUIÇÃO

SIM ...


... Ele produz de fato


SABERES


que servem para a


COMPREENSÃO IMEDIATA


do mundo e da sociedade ...


SENSO COMUM

INTUIÇÃO

RISCOS DO CONHECIMENTO INTUITIVO:



Parece auto-evidente,

o que reduz a nossa vontade de testar a sua validade

SENSO COMUM

INTUIÇÃO

(2) A TRADIÇÃO
A tradição teve origem da necessidade de


DIVULGARMOS e COMPARTILHARMOS

o conhecimento espontâneo ...


Nossas experiências, o que nos falam, nos contam,

e que achamos útil ...


SENSO COMUM

A TRADIÇÃO transmite saber que

parece verdadeiro e útil para todos ...


... no passado, no presente e no futuro ...


SENSO COMUM

TRADIÇÃO

A TRADIÇÃO dita o que se deve conhecer ...


... muitas vezes, sem qualquer fundamento ...



SENSO COMUM

TRADIÇÃO

Mas é um conhecimento ...


E TAMBÉM ÚTIL !!!

SENSO COMUM

TRADIÇÃO

Exemplos do conhecimento baseado na tradição (A)
- A superstição: o número 13




SENSO COMUM

TRADIÇÃO

As “proibições” e “combinações”

alimentares não racionalizadas:


leite com manga faz mal


frutos do mar com queijo não combinam


SENSO COMUM

TRADIÇÃO

Exemplos (B)

As proibições semi-racionalizadas:


passar debaixo de uma escada


(por que algo pode cair)


SENSO COMUM

TRADIÇÃO

Exemplos (C)

Os tabus sociais:


a proibição do incesto

e dos

casamentos consangüíneos


SENSO COMUM

TRADIÇÃO

Exemplos (D)

(3) A AUTORIDADE
Se encarrega da transmissão da tradição de forma COERCITIVA.




Papel midiático, governos, força indevida ...



SENSO COMUM

Existem razões históricas do sucesso do

SABER AUTORITÁRIO:


comodidade para condução da vida a partir de um repertório de saber alheio, já pronto e dado

SENSO COMUM

Um exemplo do conhecimento autoritário

A ESCOLA TRADICIONAL:

autoridades pedagógicas escolhem o conhecimento que parece útil ou necessário


... Apenas parte deste conhecimento são transmitidas,

sem que os estudantes sejam convidados

a determinar o seu sentido e limites ...


SENSO COMUM

AUTORIDADE

Outro exemplo do conhecimento baseado na autoridade: o conhecimento MITOLÓGICO e/ou RELIGIOSO
Os mitos/deuses como respostas às

inquietações do homem sobre o mundo e seu funcionamento


SENSO COMUM

AUTORIDADE

O estabelecimento de

REGRAS OU PRECEITOS RELIGIOSOS,

cuja origem ou sentido não são sempre evidentes, embora possam ser, em sua maior parte,


HISTORICAMENTE RASTREADOS

SENSO COMUM

AUTORIDADE

Qual é o valor do CONHECIMENTO AUTORITÁRIO ou imposto?
SENSO COMUM

AUTORIDADE


O valor do

CONHECIMENTO IMPOSTO

repousa em nosso consentimento em recebê-lo



Este consentimento depende, por sua vez, na confiança que temos naqueles que o veiculam

SENSO COMUM

AUTORIDADE

AFINAL DE CONTAS,

QUAIS SÃO AS


VANTAGENS E DESVANTAGENS


DO CONHECIMENTO DO


SENSO COMUM ????????

SENSO COMUM

Vantagens (1)
Por sua espontaneidade e acessibilidade, permite a


SOLUÇÃO RÁPIDA


de muitos de nossos problemas imediatos



SENSO COMUM

Vantagens (2)
É CÔMODO

porque não exige planejamento ou programação.


Desenvolve-se à medida que a vida vai acontecendo


SENSO COMUM

Vantagens

Vantagens (3)
É um conhecer sem o trabalho da reflexão e do teste crítico

SENSO COMUM

Vantagens

Desvantagens (1)
Caráter utilitarista, sem um aprofundamento crítico


Utilizamos o conhecimento que

“funciona¨,

sem compreendermos as razões do seu sucesso


Exemplo: o uso de plantas medicinais

SENSO COMUM

Desvantagens (2)
Subjetividade e baixo poder de crítica


O senso comum, por estar demasiadamente preso à vivência e à percepção sensorial imediata, exclui tudo que não se enquadra em um enfoque de caráter utilitário


Por outro lado, é

FORTEMENTE SUSTENTADO PELAS CRENÇAS PESSOAIS

SENSO COMUM

Desvantagens

Desvantagens (3)
Linguagem vaga:


Termos distintos são utilizados para os mesmos objetos por vários sujeitos sem que haja uma definição clara e consensual que especifique as suas condições de uso


Isto dificulta o controle e a comprovação experimental


Exemplos: os nomes vulgares de plantas e animais


SENSO COMUM

Desvantagens

Desvantagens (4)
Desconhecimento dos limites de validade


Muitas vezes, no senso comum, apesar de se modificarem as condições determinantes de um fato, continuamos a utilizar as mesmas técnicas, procedimentos e conhecimentos


Exemplo: a baixa adaptabilidade da agricultura tradicional

SENSO COMUM

Desvantagens

AS ORIGENS DO “CONHECIMENTO CIENTÍFICO”
Insatisfação do homem frente ao

CONHECIMENTO EMPÍRICO PASSIVO,

que limita seu poder de modificar ou controlar os fenômenos da natureza



Desejo de saber mais, usando também a

LÓGICA e a RAZÃO

como uma

FORMA SISTEMÁTICA, METÓDICA e CRÍTICA

de compreender o mundo,

lançando mão de princípios explicativos mais gerais e compreensivos


... e que trazem muitos benefícios para a sociedade ...

AS ORIGENS DO “CONHECIMENTO CIENTÍFICO”

As bases do pensamento científico (1)

Observação empírica do concreto e sua


INTERPRETAÇÃO PELA MENTE,


com a proposição de uma explicação,


DE CARÁTER ESPECULATIVO


SABER CIENTÍFICO

As bases do pensamento científico (2)


Colocação da explicação à prova,

através das próprias observações e da experimentação


SABER CIENTÍFICO

As bases do pensamento científico (3)


Desta forma, o conhecimento deixa de se basear apenas na especulação, para se basear na


OBSERVAÇÃO, EXPERIMENTAÇÃO e REFLEXÃO CRÍTICA

SABER CIENTÍFICO

O QUE É FAZER CIÊNCIA OU UMA PESQUISA CIENTÍFICA?

É perceber um

PROBLEMA

(que é a pergunta de pesquisa)

e pensar que esta situação poderia ser compreendida ou resolvida por meio de explicações ou soluções possíveis



Deve-se oferecer tais explicações

(hipóteses de trabalho)


SABER CIENTÍFICO

O QUE É FAZER CIÊNCIA OU UMA PESQUISA CIENTÍFICA? (1)
Testar estas explicações


Ter a percepção de que este novo conhecimento é mais seguro e confiável, na medida em que ele pode ser usado para gerar novos conhecimentos

SABER CIENTÍFICO

Existe um MÉTODO para fazermos CIÊNCIA?

Se pensarmos no método científico como um conjunto de regras precisas e fáceis,

a resposta é NÃO


SABER CIENTÍFICO

Se pensamos no

MÉTODO CIENTÍFICO

como um

CONJUNTO DE REGRAS E ATITUDES

para procurarmos e testarmos criticamente as melhores suposições ou explicações propostas para fatos que desconhecemos,

a resposta é

SIM

SABER CIENTÍFICO



Geralmente colocamos uma

GRANDE IMPORTÂNCIA NA CERTEZA,

enquanto que

RARAS VEZES

enfatizamos


A IMPORTÂNCIA DE UMA DÚVIDA CONSTRUTIVA ...

SABER CIENTÍFICO



Então

UMA NOVA PERGUNTA SURGE,

algo a ser respondido ...


mas sabendo que alguém deve, talvez, ter pensado/imaginado isto ...


“trabalhos anteriores/referencial teórico”

SABER CIENTÍFICO

Qualquer que seja o assunto que o cientista encontra ou onde ele o encontra, ele continua apresentando a mesma velha questão:


QUEM DISSE ISTO?


POR QUE?


QUAIS SÃO OS DADOS?


ONDE ESTÁ A PROVA (TESTE, HIPÓTESE)?

SABER CIENTÍFICO

O DEVER DA ESCOLA (OU DO ENSINO) ... DA ACADEMIA
Tem a missão

ENSINAR O MODO DE CONSTRUÇÃO DO SABER,

para que os estudantes possam ser capazes

de julgar o saber oferecido ou de construir,


POR SI MESMOS,

SEJA PELO SENSO COMUM,

OU PELO

SABER CIENTÍFICO,


... UM SABER DIFERENTE ...
